name:    espial
synopsis: Espial is an open-source, web-based bookmarking server.
version: "0.0.5"
description: ! '

  Espial is an open-source, web-based bookmarking server.

  - Yesod + PureScript + sqlite3

  - multi-user (w/ privacy scopes)
  
  - tags, stars, editing, deleting
'
category: Web
author: Jon Schoning
maintainer: jonschoning@gmail.com
copyright: Copyright (c) 2018 Jon Schoning
license: MIT
homepage: https://github.com/jonschoning/espial
git: git://github.com/jonschoning/espial.git
bug-reports: https://github.com/jonschoning/espial/issues
extra-source-files:
- README.md
- changelog.md
- config/favicon.ico
- config/keter.yml
- config/robots.txt
- config/routes
- config/settings.yml
- config/test-settings.yml
- templates/**
- static/css/**
- static/images/**
- static/js/**
- purs/Makefile
- purs/psc-package.json
- purs/src/**
- purs/test/**

default-extensions:
- BangPatterns
- CPP
- ConstraintKinds
- DeriveDataTypeable
- DeriveGeneric
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NoImplicitPrelude
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- ViewPatterns

dependencies:

# Due to a bug in GHC 8.0.1, we block its usage
# See: https://ghc.haskell.org/trac/ghc/ticket/12130
- base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5

- classy-prelude-yesod >=0.10.2 && <1.0 || >=1.1

- aeson >=0.11.1
- bcrypt >= 0.0.8
- bytestring >=0.9
- case-insensitive
- classy-prelude >=0.10.2
- classy-prelude-conduit >=0.10.2
- conduit >=1.0
- containers
- data-default
- directory >=1.1
- ekg
- ekg-core
- esqueleto
- fast-logger >=2.2
- file-embed
- foreign-store
- hjsmin >=0.1
- hscolour
- http-conduit >=2.1
- iso8601-time >=0.1.3
- microlens
- monad-control >=0.3
- monad-logger >=0.3
- monad-metrics
- mtl
- persistent >=2.0
- persistent-sqlite >=2.6.2
- persistent-template >=2.0
- pinboard
- pretty-show
- safe
- shakespeare >=2.0
- template-haskell
- text >=0.11
- time
- transformers >= 0.2.2
- unordered-containers
- vector
- wai
- wai-extra >=3.0
- wai-logger >=2.2
- wai-middleware-metrics
- warp >=3.0
- yaml >=0.8
- yesod >=1.4.3
- yesod-auth >=1.4.0
- yesod-core >=1.4.30
- yesod-form >=1.4.0
- yesod-static >=1.4.0.3


# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  espial:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - espial
    when:
    - condition: flag(library-only)
      buildable: false
  migration:
    when:
      - condition: flag(library-only)
        buildable: false
    main: Main.hs
    source-dirs:
      - app/migration
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - espial
      - optparse-generic >= 1.2.3

# Test suite
tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - espial
    - hspec >=2.0.0
    - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
